version: '3.8'

services:
  borgmatic-ui:
    image: borgmatic-web-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    
    # Portainer-friendly labels
    labels:
      - "com.docker.stack.namespace=borgmatic-ui"
      - "traefik.enable=true"
      - "traefik.http.routers.borgmatic-ui.rule=Host(`borgmatic.local`)"
      - "traefik.http.services.borgmatic-ui.loadbalancer.server.port=8000"
      - "traefik.docker.network=borgmatic-network"
    
    ports:
      - "7879:8000"
    
    volumes:
      # Configuration and data volumes
      - borgmatic_config:/app/config:rw
      - borgmatic_backups:/backups:rw
      - borgmatic_logs:/app/logs:rw
      - borgmatic_data:/app/data:rw
      
      # System volumes for cron and SSH
      - /etc/cron.d:/etc/cron.d:ro
      - /etc/localtime:/etc/localtime:ro
    
    environment:
      # Application settings
      - BORGMATIC_CONFIG_PATH=/app/config/borgmatic.yaml
      - BORGMATIC_BACKUP_PATH=/backups
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - ENVIRONMENT=production
      
      # Cron settings
      - ENABLE_CRON_BACKUPS=${ENABLE_CRON_BACKUPS:-false}
      
      # Database settings
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./borgmatic.db}
      
      # CORS settings
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:7879","http://localhost:8000"]}
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    
    networks:
      - borgmatic-network

  # PostgreSQL for production use
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=borgmatic
      - POSTGRES_USER=borgmatic
      - POSTGRES_PASSWORD=${DB_PASSWORD:-borgmatic123}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U borgmatic -d borgmatic"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    
    networks:
      - borgmatic-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-borgmatic123}
    
    volumes:
      - redis_data:/data
    
    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    
    networks:
      - borgmatic-network

networks:
  borgmatic-network:
    driver: overlay
    name: borgmatic-network

volumes:
  borgmatic_config:
    driver: local
    name: borgmatic-config
  borgmatic_backups:
    driver: local
    name: borgmatic-backups
  borgmatic_logs:
    driver: local
    name: borgmatic-logs
  borgmatic_data:
    driver: local
    name: borgmatic-data
  postgres_data:
    driver: local
    name: borgmatic-postgres-data
  redis_data:
    driver: local
    name: borgmatic-redis-data
