services:
  borgmatic-ui:
    # Use pre-built image from Docker Hub (RECOMMENDED - instant startup!)
    # Replace 'ainullcode' with your actual Docker Hub username if different
    image: ${DOCKER_IMAGE:-ainullcode/borgmatic-ui:latest}

    # OR build locally (only for development - takes 20-40 mins on Pi)
    # Uncomment the line below and comment out 'image' above to build locally:
    # build: .

    container_name: borgmatic-web-ui
    
    # Portainer-friendly labels
    labels:
      - "com.docker.compose.project=borgmatic-ui"
      - "com.docker.compose.service=borgmatic-ui"
      - "traefik.enable=true"
      - "traefik.http.routers.borgmatic-ui.rule=Host(`borgmatic.local`)"
      - "traefik.http.services.borgmatic-ui.loadbalancer.server.port=8000"

    # Port mapping
    # Note: Not needed when using network_mode: "host"
    # ports:
    #   - "8000:8000"

    volumes:
      # Configuration and data volumes
      - ./config:/app/config:rw
      - ./backups:/backups:rw
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw

      # System volumes for cron and SSH
      - /etc/cron.d:/etc/cron.d:ro
      - /etc/localtime:/etc/localtime:ro

      # SSH socket forwarding (for accessing host SSH keys if needed)
      # - ~/.ssh:/root/.ssh:ro
      
      # Optional: Mount host directories for backup sources
      # - /path/to/backup/source:/backup-source:ro
    
    environment:
      # Application settings
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - BORGMATIC_CONFIG_PATH=/app/config/borgmatic.yaml
      - BORGMATIC_BACKUP_PATH=/backups
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # Security settings (⚠️ MUST set in .env file!)
      - SECRET_KEY=${SECRET_KEY:?ERROR: SECRET_KEY is required! Set it in .env file}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - STRICT_SECURITY=${STRICT_SECURITY:-false}
      
      # Cron settings
      - ENABLE_CRON_BACKUPS=${ENABLE_CRON_BACKUPS:-false}

      # Database settings (SQLite - persists in ./data directory)
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/borgmatic.db}
      
      # CORS settings
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:7879","http://localhost:8000"]}
    
    restart: unless-stopped

    # Use host network for direct access to host network interfaces
    # Allows the container to access SSH servers on the host and local network
    network_mode: "host"

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'