"""Add rclone-backed repository storage tables."""

from sqlalchemy import inspect, text


def _migration_bind(db):
    return db.get_bind() if hasattr(db, "get_bind") else db


def _table_exists(db, table_name: str) -> bool:
    return inspect(_migration_bind(db)).has_table(table_name)


def _id_primary_key(db) -> str:
    dialect_name = _migration_bind(db).dialect.name
    if dialect_name == "postgresql":
        return "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "id INTEGER PRIMARY KEY"


def _timestamp_type(db) -> str:
    dialect_name = _migration_bind(db).dialect.name
    if dialect_name == "postgresql":
        return "TIMESTAMP"
    return "DATETIME"


def upgrade(db):
    id_primary_key = _id_primary_key(db)
    timestamp_type = _timestamp_type(db)
    if not _table_exists(db, "rclone_remotes"):
        db.execute(
            text(
                f"""
                CREATE TABLE rclone_remotes (
                    {id_primary_key},
                    name VARCHAR NOT NULL UNIQUE,
                    provider VARCHAR NOT NULL,
                    config_source VARCHAR NOT NULL DEFAULT 'managed',
                    config_path VARCHAR,
                    redacted_config JSON,
                    last_tested_at {timestamp_type},
                    last_test_status VARCHAR NOT NULL DEFAULT 'unknown',
                    last_error TEXT,
                    created_at {timestamp_type} NOT NULL,
                    updated_at {timestamp_type} NOT NULL
                )
                """
            )
        )
        db.execute(text("CREATE INDEX ix_rclone_remotes_id ON rclone_remotes (id)"))
        db.execute(text("CREATE INDEX ix_rclone_remotes_name ON rclone_remotes (name)"))

    if not _table_exists(db, "repository_storage"):
        db.execute(
            text(
                f"""
                CREATE TABLE repository_storage (
                    {id_primary_key},
                    repository_id INTEGER NOT NULL UNIQUE,
                    backend VARCHAR NOT NULL DEFAULT 'local',
                    rclone_remote_id INTEGER,
                    rclone_remote_path VARCHAR,
                    cache_path VARCHAR,
                    sync_policy VARCHAR NOT NULL DEFAULT 'after_success',
                    sync_direction VARCHAR NOT NULL DEFAULT 'cache_to_remote',
                    sync_status VARCHAR NOT NULL DEFAULT 'pending',
                    last_synced_at {timestamp_type},
                    last_hydrated_at {timestamp_type},
                    last_remote_check_at {timestamp_type},
                    last_sync_error TEXT,
                    extra_flags JSON,
                    created_at {timestamp_type} NOT NULL,
                    updated_at {timestamp_type} NOT NULL,
                    FOREIGN KEY(repository_id) REFERENCES repositories(id) ON DELETE CASCADE,
                    FOREIGN KEY(rclone_remote_id) REFERENCES rclone_remotes(id) ON DELETE SET NULL
                )
                """
            )
        )
        db.execute(
            text("CREATE INDEX ix_repository_storage_id ON repository_storage (id)")
        )
        db.execute(
            text(
                "CREATE INDEX ix_repository_storage_repository_id "
                "ON repository_storage (repository_id)"
            )
        )

    if not _table_exists(db, "rclone_sync_jobs"):
        db.execute(
            text(
                f"""
                CREATE TABLE rclone_sync_jobs (
                    {id_primary_key},
                    repository_id INTEGER NOT NULL,
                    direction VARCHAR NOT NULL,
                    status VARCHAR NOT NULL DEFAULT 'pending',
                    started_at {timestamp_type},
                    completed_at {timestamp_type},
                    bytes_transferred BIGINT,
                    files_transferred INTEGER,
                    log_path VARCHAR,
                    error_text TEXT,
                    created_at {timestamp_type} NOT NULL,
                    FOREIGN KEY(repository_id) REFERENCES repositories(id) ON DELETE CASCADE
                )
                """
            )
        )
        db.execute(text("CREATE INDEX ix_rclone_sync_jobs_id ON rclone_sync_jobs (id)"))
        db.execute(
            text(
                "CREATE INDEX ix_rclone_sync_jobs_repository_id "
                "ON rclone_sync_jobs (repository_id)"
            )
        )

    db.commit()


def downgrade(db):
    if _table_exists(db, "rclone_sync_jobs"):
        db.execute(text("DROP TABLE rclone_sync_jobs"))
    if _table_exists(db, "repository_storage"):
        db.execute(text("DROP TABLE repository_storage"))
    if _table_exists(db, "rclone_remotes"):
        db.execute(text("DROP TABLE rclone_remotes"))
    db.commit()
