"""Add reusable script hook assignments to backup plans."""

from sqlalchemy import inspect, text


def _bind(db):
    return db.get_bind() if hasattr(db, "get_bind") else db


def _table_exists(db, table_name: str) -> bool:
    return inspect(_bind(db)).has_table(table_name)


def _id_primary_key(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "id INTEGER PRIMARY KEY"


def _timestamp_type(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "TIMESTAMP"
    return "DATETIME"


def _bool_default(value: bool, db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "TRUE" if value else "FALSE"
    return "1" if value else "0"


def upgrade(db):
    if not _table_exists(db, "backup_plan_scripts"):
        true_default = _bool_default(True, db)
        false_default = _bool_default(False, db)
        db.execute(
            text(
                f"""
                CREATE TABLE backup_plan_scripts (
                    {_id_primary_key(db)},
                    backup_plan_id INTEGER NOT NULL,
                    script_id INTEGER NOT NULL,
                    hook_type VARCHAR(50) NOT NULL,
                    execution_order FLOAT NOT NULL DEFAULT 1,
                    enabled BOOLEAN NOT NULL DEFAULT {true_default},
                    custom_timeout INTEGER,
                    custom_run_on VARCHAR(50),
                    continue_on_error BOOLEAN DEFAULT {false_default},
                    skip_on_failure BOOLEAN DEFAULT {false_default},
                    parameter_values TEXT,
                    created_at {_timestamp_type(db)} NOT NULL,
                    CONSTRAINT uq_backup_plan_script UNIQUE (backup_plan_id, script_id, hook_type),
                    FOREIGN KEY(backup_plan_id) REFERENCES backup_plans(id) ON DELETE CASCADE,
                    FOREIGN KEY(script_id) REFERENCES scripts(id) ON DELETE CASCADE
                )
                """
            )
        )
        db.execute(
            text("CREATE INDEX ix_backup_plan_scripts_id ON backup_plan_scripts (id)")
        )
        db.execute(
            text(
                "CREATE INDEX ix_backup_plan_scripts_backup_plan_id "
                "ON backup_plan_scripts (backup_plan_id)"
            )
        )
        db.execute(
            text(
                "CREATE INDEX ix_backup_plan_scripts_script_id "
                "ON backup_plan_scripts (script_id)"
            )
        )
    db.commit()


def downgrade(db):
    if _table_exists(db, "backup_plan_scripts"):
        db.execute(text("DROP TABLE backup_plan_scripts"))
    db.commit()
