"""Add retry lineage for backup jobs and backup plan runs."""

from sqlalchemy import inspect, text


def _bind(db):
    return db.get_bind() if hasattr(db, "get_bind") else db


def _columns(db, table_name: str) -> set[str]:
    return {column["name"] for column in inspect(_bind(db)).get_columns(table_name)}


def _table_exists(db, table_name: str) -> bool:
    return inspect(_bind(db)).has_table(table_name)


def _id_primary_key(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "id INTEGER PRIMARY KEY"


def _timestamp_type(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "TIMESTAMP"
    return "DATETIME"


def _json_type(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "JSONB"
    return "JSON"


def _add_column_if_missing(db, table_name: str, column_name: str, ddl: str) -> None:
    if column_name not in _columns(db, table_name):
        db.execute(text(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {ddl}"))


def _create_index(db, name: str, table_name: str, column_name: str) -> None:
    db.execute(
        text(f"CREATE INDEX IF NOT EXISTS {name} ON {table_name} ({column_name})")
    )


def _sqlite_supports_drop_column(db) -> bool:
    version = db.execute(text("SELECT sqlite_version()")).scalar() or "0.0.0"
    return tuple(int(part) for part in version.split(".")[:3]) >= (3, 35, 0)


def _drop_column_if_exists(db, table_name: str, column_name: str) -> None:
    if column_name not in _columns(db, table_name):
        return
    if _bind(db).dialect.name == "sqlite" and not _sqlite_supports_drop_column(db):
        print(
            f"SQLite version does not support DROP COLUMN; "
            f"{table_name}.{column_name} will remain"
        )
        return
    db.execute(text(f"ALTER TABLE {table_name} DROP COLUMN {column_name}"))


def upgrade(db):
    timestamp_type = _timestamp_type(db)

    _add_column_if_missing(
        db,
        "backup_jobs",
        "retry_original_job_id",
        "INTEGER REFERENCES backup_jobs(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_jobs",
        "retry_source_job_id",
        "INTEGER REFERENCES backup_jobs(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_jobs",
        "retry_attempt",
        "INTEGER NOT NULL DEFAULT 1",
    )
    _add_column_if_missing(
        db,
        "backup_jobs",
        "retry_requested_by_user_id",
        "INTEGER REFERENCES users(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_jobs",
        "retry_requested_at",
        timestamp_type,
    )

    _add_column_if_missing(
        db,
        "backup_plan_runs",
        "retry_original_run_id",
        "INTEGER REFERENCES backup_plan_runs(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_plan_runs",
        "retry_source_run_id",
        "INTEGER REFERENCES backup_plan_runs(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_plan_runs",
        "retry_attempt",
        "INTEGER NOT NULL DEFAULT 1",
    )
    _add_column_if_missing(
        db,
        "backup_plan_runs",
        "retry_requested_by_user_id",
        "INTEGER REFERENCES users(id) ON DELETE SET NULL",
    )
    _add_column_if_missing(
        db,
        "backup_plan_runs",
        "retry_requested_at",
        timestamp_type,
    )

    if not _table_exists(db, "backup_job_retry_lineage"):
        db.execute(
            text(
                f"""
                CREATE TABLE backup_job_retry_lineage (
                    {_id_primary_key(db)},
                    original_job_id INTEGER REFERENCES backup_jobs(id) ON DELETE SET NULL,
                    retry_source_job_id INTEGER REFERENCES backup_jobs(id) ON DELETE SET NULL,
                    attempt_number INTEGER NOT NULL,
                    requested_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    requested_at {timestamp_type} NOT NULL,
                    created_job_id INTEGER UNIQUE REFERENCES backup_jobs(id) ON DELETE SET NULL,
                    request_snapshot {_json_type(db)} NOT NULL
                )
                """
            )
        )

    if not _table_exists(db, "backup_plan_run_retry_lineage"):
        db.execute(
            text(
                f"""
                CREATE TABLE backup_plan_run_retry_lineage (
                    {_id_primary_key(db)},
                    original_run_id INTEGER REFERENCES backup_plan_runs(id) ON DELETE SET NULL,
                    retry_source_run_id INTEGER REFERENCES backup_plan_runs(id) ON DELETE SET NULL,
                    attempt_number INTEGER NOT NULL,
                    requested_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    requested_at {timestamp_type} NOT NULL,
                    created_run_id INTEGER UNIQUE REFERENCES backup_plan_runs(id) ON DELETE SET NULL,
                    request_snapshot {_json_type(db)} NOT NULL
                )
                """
            )
        )

    for table_name, columns in {
        "backup_jobs": [
            "retry_original_job_id",
            "retry_source_job_id",
            "retry_requested_by_user_id",
        ],
        "backup_plan_runs": [
            "retry_original_run_id",
            "retry_source_run_id",
            "retry_requested_by_user_id",
        ],
        "backup_job_retry_lineage": [
            "original_job_id",
            "retry_source_job_id",
            "created_job_id",
            "requested_by_user_id",
        ],
        "backup_plan_run_retry_lineage": [
            "original_run_id",
            "retry_source_run_id",
            "created_run_id",
            "requested_by_user_id",
        ],
    }.items():
        for column_name in columns:
            _create_index(db, f"ix_{table_name}_{column_name}", table_name, column_name)

    db.commit()


def downgrade(db):
    if _table_exists(db, "backup_plan_run_retry_lineage"):
        db.execute(text("DROP TABLE backup_plan_run_retry_lineage"))
    if _table_exists(db, "backup_job_retry_lineage"):
        db.execute(text("DROP TABLE backup_job_retry_lineage"))

    for table_name, columns in {
        "backup_plan_runs": [
            "retry_requested_at",
            "retry_requested_by_user_id",
            "retry_attempt",
            "retry_source_run_id",
            "retry_original_run_id",
        ],
        "backup_jobs": [
            "retry_requested_at",
            "retry_requested_by_user_id",
            "retry_attempt",
            "retry_source_job_id",
            "retry_original_job_id",
        ],
    }.items():
        for column_name in columns:
            _drop_column_if_exists(db, table_name, column_name)

    db.commit()
