"""Add provider-keyed rclone OAuth credentials."""

from sqlalchemy import inspect, text


def _bind(db):
    return db.get_bind() if hasattr(db, "get_bind") else db


def _table_exists(db, table_name: str) -> bool:
    return inspect(_bind(db)).has_table(table_name)


def _timestamp_type(db) -> str:
    return "TIMESTAMP" if _bind(db).dialect.name == "postgresql" else "DATETIME"


def _id_primary_key(db) -> str:
    if _bind(db).dialect.name == "postgresql":
        return "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "id INTEGER PRIMARY KEY"


def upgrade(db):
    if not _table_exists(db, "rclone_oauth_provider_credentials"):
        timestamp_type = _timestamp_type(db)
        db.execute(
            text(
                "CREATE TABLE rclone_oauth_provider_credentials ("
                f"{_id_primary_key(db)}, "
                "provider VARCHAR NOT NULL UNIQUE, "
                "client_id VARCHAR, "
                "client_secret_encrypted VARCHAR, "
                f"created_at {timestamp_type} NOT NULL, "
                f"updated_at {timestamp_type} NOT NULL"
                ")"
            )
        )
        db.execute(
            text(
                "CREATE INDEX ix_rclone_oauth_provider_credentials_id "
                "ON rclone_oauth_provider_credentials (id)"
            )
        )
        db.execute(
            text(
                "CREATE UNIQUE INDEX ix_rclone_oauth_provider_credentials_provider "
                "ON rclone_oauth_provider_credentials (provider)"
            )
        )
    db.commit()


def downgrade(db):
    if _table_exists(db, "rclone_oauth_provider_credentials"):
        db.execute(text("DROP TABLE rclone_oauth_provider_credentials"))
    db.commit()
