#!/usr/bin/env bash
#
# Builds the release tarball that scripts/install.sh downloads: the application
# source, the prebuilt frontend bundle, the managed-agent wheelhouse and the
# packaging assets, plus the pinned Borg/rclone versions the installer needs.
#
#   ./scripts/build-native-tarball.sh [output-dir]
#
# Nothing in here is version-specific by hand: every pin is read from
# docker/runtime-base.env and Dockerfile.runtime-base, the same sources the
# image builds from, so the native install can never drift from the container.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

mkdir -p "${1:-dist}"
OUT_DIR="$(cd "${1:-dist}" && pwd)"

VERSION="$(tr -d '[:space:]' <VERSION)"
NAME="borg-ui-${VERSION}"
STAGE="$(mktemp -d)"/"${NAME}"
trap 'rm -rf "$(dirname "${STAGE}")"' EXIT

echo "==> Building ${NAME}"
mkdir -p "${STAGE}"

# --- frontend --------------------------------------------------------------
echo "==> Building the frontend bundle"
npm --prefix frontend ci
npm --prefix frontend run build

# --- managed-agent wheelhouse ----------------------------------------------
# The wheelhouse a native server hands to enrolling nodes, built the same way
# the Dockerfile's agent-builder stage builds it: forced to py3-none-any so one
# wheelhouse serves nodes of any architecture, and version-pinned through
# agent/constraints.txt so the same commit always stages the same wheels.
echo "==> Building the managed-agent wheelhouse"
python3 -m pip install --quiet --upgrade build
python3 -m build --wheel --outdir "${STAGE}/agent-dist" >/dev/null
python3 -m pip download --quiet --only-binary=:all: \
  --implementation py --abi none --platform any \
  --constraint agent/constraints.txt \
  --dest "${STAGE}/agent-dist" "${STAGE}"/agent-dist/borg_ui_agent-*.whl

# --- application -----------------------------------------------------------
echo "==> Staging the application"
cp -R app "${STAGE}/app"
find "${STAGE}/app" -name '__pycache__' -type d -prune -exec rm -rf {} +
rm -rf "${STAGE}/app/static"
cp -R frontend/build "${STAGE}/app/static"

cp VERSION requirements.txt "${STAGE}/"
mkdir -p "${STAGE}/packaging" "${STAGE}/scripts"
cp -R packaging/native "${STAGE}/packaging/native"
cp scripts/install.sh "${STAGE}/scripts/install.sh"

# --- pinned versions -------------------------------------------------------
# The installer sources this instead of carrying constants of its own.
echo "==> Recording the pinned Borg and rclone versions"
# shellcheck source=docker/runtime-base.env
source docker/runtime-base.env

dockerfile_arg() {
  grep -m1 "^ARG $1=" Dockerfile.runtime-base | cut -d= -f2-
}

{
  echo "# Generated by scripts/build-native-tarball.sh -- do not edit."
  echo "# Pins copied from docker/runtime-base.env and Dockerfile.runtime-base."
  echo "BORG1_VERSION=${BORG1_VERSION}"
  echo "BORG2_VERSION=${BORG2_VERSION}"
  echo "BORGSTORE_VERSION=${BORGSTORE_VERSION}"
  echo "RCLONE_VERSION=${RCLONE_VERSION}"
  echo "RCLONE_SHA256_AMD64=$(dockerfile_arg RCLONE_SHA256_AMD64)"
  echo "RCLONE_SHA256_ARM64=$(dockerfile_arg RCLONE_SHA256_ARM64)"
} >"${STAGE}/packaging/native/versions.env"

for key in BORG2_VERSION BORGSTORE_VERSION RCLONE_VERSION RCLONE_SHA256_AMD64 RCLONE_SHA256_ARM64; do
  grep -q "^${key}=..*" "${STAGE}/packaging/native/versions.env" ||
    { echo "error: ${key} came out empty; the pin sources have moved" >&2; exit 1; }
done

# --- tarball ---------------------------------------------------------------
mkdir -p "${OUT_DIR}"
tar -czf "${OUT_DIR}/${NAME}.tar.gz" -C "$(dirname "${STAGE}")" "${NAME}"
(cd "${OUT_DIR}" && sha256sum "${NAME}.tar.gz" >"${NAME}.tar.gz.sha256")

echo "==> ${OUT_DIR}/${NAME}.tar.gz"
cat "${OUT_DIR}/${NAME}.tar.gz.sha256"
